---
openapi: 3.0.1
info:
  title: Weather Test API V1
  version: v1
paths:
  "/api/v1/average_temperature":
    get:
      summary: Retrieves the average temperature
      tags:
      - AverageTemperature
      parameters:
      - name: cities
        in: query
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: average temperature retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  average_temperature:
                    type: number
                    format: float
                  unit:
                    type: string
                  cities:
                    type: array
                    items:
                      type: string
        '422':
          description: City is not in the list
          content:
            application/json:
              examples:
                example_0:
                  value:
                    error: Berlin is not included in the list
        '401':
          description: unauthorized
  "/api/v1/sessions":
    post:
      summary: Creates a session
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: session created
        '401':
          description: wrong credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password
                prefered_city:
                  type: string
                  example: Paris
              required:
              - email
              - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
